# Generated by Django 3.0 on 2020-06-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=1000)),
                ('valor', models.IntegerField()),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('tipo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'custos',
                'managed': True,
            },
        ),
    ]
