# Generated by Django 3.0 on 2020-06-01 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custos',
            old_name='tipo',
            new_name='credito',
        ),
    ]
